chore: Hiero renaming initial
hiero-ledger/hiero-sdk-go pull request #1152
Opened 2024-11-20 14:17 UTC by gsstoykov

**Description**:
This PR introduces Hiero renaming for the C++ SDK.

**Related issue(s)**:

Fixes https://github.com/hiero-ledger/hiero-sdk-go/issues/1081

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-11-20 15:13 UTC, rbarkerSL requested changes

2024-11-20 15:13 UTC, rbarkerSL commented on .github/CODEOWNERS
My suggested updates

```text
# Default code owners for entire repository
*                                               @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
#########################
#####  Core Files  ######
#########################
# NOTE: Must be placed last to ensure enforcement over all other rules

# Protection Rules for Github Configuration Files and Actions Workflows
/.github/                                       @hiero-ledger/github-maintainers @hiero-ledger/github-committers
/.github/workflows/                             @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers

# Legacy Maven project files
**/pom.xml                                      @hiero-ledger/github-maintainers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers

# Gradle project files and inline plugins
/gradle/                                        @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
gradlew                                         @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
gradlew.bat                                     @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
**/build-logic/                                 @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
**/gradle.*                                     @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
**/*.gradle.*                                   @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers

# Codacy Tool Configurations
/config/                                        @hiero-ledger/github-maintainers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
.remarkrc                                       @hiero-ledger/github-maintainers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers

# Self-protection for root CODEOWNERS files (this file should not exist and should definitely require approval)
/CODEOWNERS                                     @hiero-ledger/github-maintainers

# Protect the repository root files
/README.md                                      @hiero-ledger/github-maintainers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers @hiero-ledger/tsc
**/LICENSE                                      @hiero-ledger/github-maintainers @hiero-ledger/tsc
```

2024-11-21 14:06 UTC, rbarkerSL requested changes
Recommend addressing merge conflicts on main.yml and updating to the latest. I believe

2024-11-21 14:06 UTC, rbarkerSL commented on .github/workflows/main.yml
Nit: whitespace got shifted dramatically.

The hashgraph standard for yaml files is two space characters ' ' per indent. I also see that the character `'` has been replaced by `"` throughout the file. Recommend reverting that.

2024-11-21 14:06 UTC, rbarkerSL commented on .github/CODEOWNERS
> +gradlew.bat                                     @hiero-ledger/github-maintainers @hiero-ledger/github-committers @hiero-ledger/hiero-sdk-go-maintainers @hiero-ledger/hiero-sdk-go-committers
```suggestion
gradlew                                         @hiero-ledger/github-maintainers @hiero-ledger/github-committers
gradlew.bat                                     @hiero-ledger/github-maintainers @hiero-ledger/github-committers
```

2024-11-26 14:32 UTC, 0xivanov approved these changes
Reviewed Go files.

2024-11-26 17:07 UTC, rbarkerSL approved these changes
Approval applies to the following files:

- .github/CODEOWNERS
- .github/workflows/main.yml
- CHANGELOG.md
- LICENSE
- README.md
- go.mod
- tck/go.mod

I would like to here from @hendrikebbers or @nathanklick on if the change to the license file should have removed the hashgraph copyright or not? but this LGTM

2024-11-27 08:13 UTC, gsstoykov commented
@rbarkerSL In C++ SDK we got it in with removing the Hashgraph copyright. We had some discussions around that topic. Will merge the PR if something comes up I will open a followup to change it.

2024-11-27 08:14 UTC, merged